
PRODUCTS = [
    
  {
    "id": 1,
    "name": "Organic Cotton T-Shirt",
    "brand": "EcoWear Co.",
    "price": 28.99,
    "original_price": 35.99,
    "rating": 4.8,
    "reviews": 12,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300",
    "labels": ["Fair Trade", "Carbon Neutral"],
    "categories": ["Fashion", "Accessories"],
    "features": ["Organic"]
  },
  {
    "id": 2,
    "name": "Bamboo Water Bottle",
    "brand": "GreenLife",
    "price": 19.99,
    "original_price": 24.99,
    "rating": 4.9,
    "reviews": 89,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300",
    "labels": ["Local", "BPA-Free"],
    "categories": ["Home", "Accessories"],
    "features": ["Zero Waste"]
  },
  {
    "id": 3,
    "name": "Recycled Phone Case",
    "brand": "ReNewTech",
    "price": 15.99,
    "original_price": 18.99,
    "rating": 4.7,
    "reviews": 156,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300",
    "labels": ["Carbon Neutral", "Durable"],
    "categories": ["Electronics", "Accessories"],
    "features": ["Recycled"]
  },
  {
    "id": 4,
    "name": "Natural Soap Set",
    "brand": "Pure Earth",
    "price": 12.99,
    "original_price": 16.99,
    "rating": 4.6,
    "reviews": 78,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300",
    "labels": ["Plastic-Free", "Organic"],
    "categories": ["Beauty", "Accessories"],
    "features": ["Vegan"]
  },
  {
    "id": 5,
    "name": "Eco Notebook",
    "brand": "Pure Earth",
    "price": 11.79,
    "original_price": 21.26,
    "rating": 4.9,
    "reviews": 318,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300?text=Product+5",
    "labels": ["Local"],
    "categories": ["Outdoor"],
    "features": ["Organic", "Compostable"]
  },
  {
    "id": 6,
    "name": "Eco Grocery Bag",
    "brand": "GreenLife",
    "price": 91.6,
    "original_price": 98.78,
    "rating": 5.0,
    "reviews": 345,
    "location": "Denver, CO",
    "image_url": "https://via.placeholder.com/300?text=Product+6",
    "labels": ["Non-Toxic", "Recycled", "Plastic-Free"],
    "categories": ["Fashion", "Beauty"],
    "features": ["Compostable", "Vegan"]
  },
  {
    "id": 7,
    "name": "Eco Sunglasses",
    "brand": "Verde",
    "price": 95.38,
    "original_price": 109.86,
    "rating": 4.5,
    "reviews": 484,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+7",
    "labels": ["Recycled"],
    "categories": ["Fashion"],
    "features": ["Organic"]
  },
  {
    "id": 8,
    "name": "Natural Hoodie",
    "brand": "EcoWear Co.",
    "price": 38.91,
    "original_price": 48.26,
    "rating": 4.6,
    "reviews": 66,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300?text=Product+8",
    "labels": ["Durable", "Non-Toxic"],
    "categories": ["Fashion", "Home"],
    "features": ["Compostable", "Vegan"]
  },
  {
    "id": 9,
    "name": "Organic Rain Jacket",
    "brand": "CleanRoots",
    "price": 34.66,
    "original_price": 46.83,
    "rating": 4.6,
    "reviews": 151,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+9",
    "labels": ["Non-Toxic"],
    "categories": ["Electronics"],
    "features": ["Compostable"]
  },
  {
    "id": 10,
    "name": "Sustainable Hoodie",
    "brand": "Sustaina",
    "price": 36.4,
    "original_price": 44.89,
    "rating": 4.4,
    "reviews": 335,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300?text=Product+10",
    "labels": ["Fair Trade", "Durable"],
    "categories": ["Beauty"],
    "features": ["Compostable"]
  },
  {
    "id": 11,
    "name": "Organic Toothbrush",
    "brand": "Sustaina",
    "price": 47.44,
    "original_price": 52.01,
    "rating": 4.7,
    "reviews": 288,
    "location": "Denver, CO",
    "image_url": "https://via.placeholder.com/300?text=Product+11",
    "labels": ["Durable"],
    "categories": ["Home", "Outdoor"],
    "features": ["Organic"]
  },
  {
    "id": 12,
    "name": "Eco Rain Jacket",
    "brand": "GreenLife",
    "price": 28.13,
    "original_price": 39.74,
    "rating": 4.9,
    "reviews": 134,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300?text=Product+12",
    "labels": ["Fair Trade", "Plastic-Free", "Carbon Neutral"],
    "categories": ["Fashion"],
    "features": ["Biodegradable"]
  },
  {
    "id": 13,
    "name": "Natural Sunglasses",
    "brand": "CleanRoots",
    "price": 77.18,
    "original_price": 90.79,
    "rating": 4.4,
    "reviews": 143,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+13",
    "labels": ["Carbon Neutral", "Durable"],
    "categories": ["Beauty", "Accessories"],
    "features": ["Zero Waste", "Organic"]
  },
  {
    "id": 14,
    "name": "Sustainable Deodorant",
    "brand": "EcoWear Co.",
    "price": 52.5,
    "original_price": 62.11,
    "rating": 4.8,
    "reviews": 379,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300?text=Product+14",
    "labels": ["Fair Trade", "Recycled"],
    "categories": ["Beauty"],
    "features": ["Vegan"]
  },
  {
    "id": 15,
    "name": "Natural Grocery Bag",
    "brand": "Verde",
    "price": 36.88,
    "original_price": 42.41,
    "rating": 4.9,
    "reviews": 226,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300?text=Product+15",
    "labels": ["Non-Toxic", "Plastic-Free"],
    "categories": ["Outdoor"],
    "features": ["Compostable", "Biodegradable"]
  },
  {
    "id": 16,
    "name": "Eco Candle",
    "brand": "CleanRoots",
    "price": 33.76,
    "original_price": 45.07,
    "rating": 4.3,
    "reviews": 105,
    "location": "Denver, CO",
    "image_url": "https://via.placeholder.com/300?text=Product+16",
    "labels": ["Fair Trade", "Durable"],
    "categories": ["Home"],
    "features": ["Zero Waste"]
  },
  {
    "id": 17,
    "name": "Natural Tote Bag",
    "brand": "EcoWear Co.",
    "price": 17.94,
    "original_price": 28.19,
    "rating": 4.5,
    "reviews": 274,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300?text=Product+17",
    "labels": ["BPA-Free", "Plastic-Free"],
    "categories": ["Accessories", "Fashion"],
    "features": ["Compostable"]
  },
  {
    "id": 18,
    "name": "Eco Yoga Mat",
    "brand": "Sustaina",
    "price": 72.82,
    "original_price": 81.07,
    "rating": 4.6,
    "reviews": 413,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+18",
    "labels": ["Fair Trade", "Local"],
    "categories": ["Fitness"],
    "features": ["Vegan", "Zero Waste"]
  },
  {
    "id": 19,
    "name": "Sustainable Socks",
    "brand": "Verde",
    "price": 30.71,
    "original_price": 42.92,
    "rating": 4.2,
    "reviews": 117,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300?text=Product+19",
    "labels": ["Carbon Neutral"],
    "categories": ["Fashion"],
    "features": ["Recycled"]
  },
  {
    "id": 20,
    "name": "Natural Face Cream",
    "brand": "GreenLife",
    "price": 26.39,
    "original_price": 32.44,
    "rating": 4.7,
    "reviews": 204,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300?text=Product+20",
    "labels": ["Organic", "BPA-Free"],
    "categories": ["Beauty"],
    "features": ["Vegan", "Biodegradable"]
  },
  {
    "id": 21,
    "name": "Organic Lunch Box",
    "brand": "Pure Earth",
    "price": 22.75,
    "original_price": 34.12,
    "rating": 4.8,
    "reviews": 188,
    "location": "Denver, CO",
    "image_url": "https://via.placeholder.com/300?text=Product+21",
    "labels": ["Durable", "Non-Toxic"],
    "categories": ["Home", "Accessories"],
    "features": ["Zero Waste", "Compostable"]
  },
  {
    "id": 22,
    "name": "Eco Compost Bin",
    "brand": "Sustaina",
    "price": 45.3,
    "original_price": 53.9,
    "rating": 4.6,
    "reviews": 264,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+22",
    "labels": ["Fair Trade", "Carbon Neutral"],
    "categories": ["Home"],
    "features": ["Compostable"]
  },
  {
    "id": 23,
    "name": "Natural Candle",
    "brand": "Verde",
    "price": 20.99,
    "original_price": 29.5,
    "rating": 4.4,
    "reviews": 148,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300?text=Product+23",
    "labels": ["Plastic-Free", "Local"],
    "categories": ["Beauty", "Home"],
    "features": ["Zero Waste"]
  },
  {
    "id": 24,
    "name": "Sustainable Slippers",
    "brand": "EcoWear Co.",
    "price": 41.55,
    "original_price": 57.28,
    "rating": 4.7,
    "reviews": 301,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300?text=Product+24",
    "labels": ["Durable"],
    "categories": ["Fashion"],
    "features": ["Recycled", "Biodegradable"]
  },
  {
    "id": 25,
    "name": "Eco Face Cream",
    "brand": "GreenLife",
    "price": 18.84,
    "original_price": 27.15,
    "rating": 4.9,
    "reviews": 227,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300?text=Product+25",
    "labels": ["Organic", "Non-Toxic", "Fair Trade"],
    "categories": ["Beauty"],
    "features": ["Vegan"]
  },
  {
    "id": 26,
    "name": "Natural Socks",
    "brand": "Verde",
    "price": 24.36,
    "original_price": 33.92,
    "rating": 4.8,
    "reviews": 163,
    "location": "Seattle, WA",
    "image_url": "https://via.placeholder.com/300?text=Product+26",
    "labels": ["Fair Trade", "Recycled"],
    "categories": ["Fashion", "Fitness"],
    "features": ["Compostable", "Zero Waste"]
  },
  {
    "id": 27,
    "name": "Eco Deodorant",
    "brand": "CleanRoots",
    "price": 14.79,
    "original_price": 21.64,
    "rating": 4.5,
    "reviews": 97,
    "location": "Portland, OR",
    "image_url": "https://via.placeholder.com/300?text=Product+27",
    "labels": ["Plastic-Free", "Non-Toxic"],
    "categories": ["Beauty"],
    "features": ["Biodegradable", "Vegan"]
  },
  {
    "id": 28,
    "name": "Sustainable Toothbrush",
    "brand": "Sustaina",
    "price": 12.45,
    "original_price": 18.73,
    "rating": 4.7,
    "reviews": 189,
    "location": "Denver, CO",
    "image_url": "https://via.placeholder.com/300?text=Product+28",
    "labels": ["Carbon Neutral", "Local"],
    "categories": ["Home"],
    "features": ["Recycled"]
  },
  {
    "id": 29,
    "name": "Eco Candle",
    "brand": "Pure Earth",
    "price": 21.95,
    "original_price": 30.12,
    "rating": 4.6,
    "reviews": 175,
    "location": "Austin, TX",
    "image_url": "https://via.placeholder.com/300?text=Product+29",
    "labels": ["Durable", "Fair Trade"],
    "categories": ["Home", "Beauty"],
    "features": ["Zero Waste"]
  },
  {
    "id": 30,
    "name": "Natural Yoga Mat",
    "brand": "GreenLife",
    "price": 66.88,
    "original_price": 78.42,
    "rating": 4.9,
    "reviews": 411,
    "location": "San Francisco, CA",
    "image_url": "https://via.placeholder.com/300?text=Product+30",
    "labels": ["Organic", "Plastic-Free"],
    "categories": ["Fitness"],
    "features": ["Biodegradable"]
  }
]

